name: "core"
description: "The core Blink plugin"
tags:
  - code
  - core
  - blink
  - internal

provider: "blink"
connection_type_reference: "aws"
connection_types:
  core-mail:
    test:
      field_type: "input"
      required: true
      placeholder: "Test"
      input_type: "text"
