name: "core"
description: "The core Blink plugin"
tags:
  - code
  - core
  - blink
  - internal

provider: "blink"
connection_types:
  core-mail:
    reference: core-mail
  aws:
    reference: aws
  kubernetes:
    reference: kubernetes
