name: "core"
icon_uri: "https://app.dev.blinkops.com/assets/images/Icons/Companies/Company/XL/Blink.svg"
description: "The core Blink plugin"
tags:
  - code
  - core
  - blink
  - internal

provider: "blink"
connection_types:
  core-mail:
    reference: core-mail
  aws:
    reference: aws
  kubernetes:
    reference: kubernetes
  gcp:
    reference: gcp
  azure:
    refernece: azure
  github:
    refernece: github
